# Generated by Django 3.0.8 on 2020-08-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlistitem',
            old_name='listing',
            new_name='listingid',
        ),
    ]
